services:
  envoy:
    image: envoyproxy/envoy:v1.24-latest
    ports:
      - "9901:9901"
      - "8081:8081"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - my_network
    depends_on:
      myid:
        condition: service_started

  myid:
    image: vochitrung/myid:latest
    env_file:
      - ./configs/myid/config.yaml
    networks:
      - my_network
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080"

  rest:
    build:
      dockerfile: ./test_rest/dockerfile
    networks:
      - my_network
    ports:
      - "8080"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: trung113
      MYSQL_DATABASE: pattern
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306"

networks:
  my_network:
